# -*- coding: utf-8 -*-
"""3Bandits#1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQBo3VMhrBD7J7dTnmhM58Gq__HjwcG1

**Stock Price Prediction for NETFLIX**
"""

#Importing the required Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Reading the Dataset
data=pd.read_csv("/content/NETFLIX.csv")
data

# Printing the first 10 rows of Data
data.head(10)

#Checing the dimensions of Data
data.shape

#Statistical Summary
data.describe()

#More information about the data
data.info()

# Data types of Variables
data.dtypes

#Checking for the null values
data.isnull().sum()